DROP TABLE TB_ALERTA_COMUNITARIO CASCADE CONSTRAINTS;
DROP TABLE TB_TRIAGEM_PRIORIDADE CASCADE CONSTRAINTS;
DROP TABLE TB_CLIMA CASCADE CONSTRAINTS;
DROP TABLE TB_ATENDIMENTO CASCADE CONSTRAINTS;
DROP TABLE TB_COMUNIDADE CASCADE CONSTRAINTS;